spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/louwailou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qpy1995
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update